unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
normalize_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
